### ISSUE TITLE
Aliases in Readme

### ISSUE THREAD

**Issue by hector-ps** [webysther/aws-glue-docker#1]
Dear @webysther,

I've reached your Docker container from:
https://github.com/awslabs/aws-glue-libs/issues/25#issuecomment-629045002

In the https://github.com/webysther/aws-glue-docker/blob/master/README.md#getting-started section the _alias_ lines are missing. Are they still necessary? 

I am really a rookie working with Glue, and I am trying to setup my local development environment on Windows to work on my scripts. Your repository has been unvaluable, but I still need some clues to make thinks work.

Thank you in advance.

**Comment by webysther** [comment]
They not necessary if you run the bash at start:

```bash
# install docker and configure aliases
curl -sSL https://raw.githubusercontent.com/webysther/aws-glue-docker/master/start.sh | sh
```

This code do the job for you, look the script `start.sh` for more details.
